services:
  web:
    build:
      context: .
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    ports:
      - 3000:3000
    volumes:
      - .:/nwgna-it-app
    env_file:
      - ".env"
    depends_on:
      - postgres

  postgres:
    image: postgres:16.4-alpine
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ".env"

volumes:
  db:
